### ISSUE TITLE
SVGO 2.3.0 and config

### ISSUE THREAD

**Issue by tkachenko1** [nuxt-modules/svg-sprite#243]
Hi :)
 
I updated the package SVGO to version 2.3.0, but the icons no longer have the width and height removed. 
What am I doing wrong? I use this config solution: https://github.com/nuxt-community/svg-sprite-module/blob/master/docs/svgo-config.md

Thanks

**Comment by tkachenko1** [comment]
thank you, I will wait for the new version

**Comment by jbrtsnts** [comment]
Any update?

**Comment by harlan-zw** [comment]
Seems like v3 is now supported in v1.
